const CFG={url:"https://ojjifayhxbtcmztljaej.supabase.co",key:"sb_publishable_S66y4SSfuFE8RySZa5UCxQ_9ZMO9J8y"};let session=null,user=null,profile=null,services=[];const $=id=>document.getElementById(id);const api=async(path,opt={})=>{const h={"apikey":CFG.key,"Content-Type":"application/json",...(opt.headers||{})};if(session?.access_token)h.Authorization="Bearer "+session.access_token;const r=await fetch(CFG.url+path,{...opt,headers:h});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error_description||t||r.status);return d};
function msg(id,x,ok=false){$(id).textContent=x;$(id).className="msg "+(ok?"ok":"")}function setOnline(){$("net").textContent=navigator.onLine?"ONLINE":"OFFLINE";$("net").className="pill"}
async function auth(type){try{const email=$("email").value.trim(),password=$("password").value;if(!email||!password)throw Error("Email dan password wajib diisi.");let d;if(type==="login")d=await api("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})});else d=await api("/auth/v1/signup",{method:"POST",body:JSON.stringify({email,password})});if(type==="signup"&&!d.access_token){msg("authMsg","Akun dibuat. Jika email confirmation aktif, konfirmasi email lalu masuk.");return}session=d;user=d.user;await loadProfile()}catch(e){msg("authMsg",e.message)}}
async function loadProfile(){const p=await api("/rest/v1/profiles?id=eq."+encodeURIComponent(user.id)+"&select=*");profile=p?.[0]||{};sessionStorage.setItem("mc_session",JSON.stringify(session));$("auth").hidden=true;$("dashboard").hidden=false;$("who").textContent=user.email||user.id;$("role").textContent=profile.role||"role belum diatur";const role=(profile.role||"").toLowerCase();$("customer").hidden=role!=="customer";$("mechanic").hidden=role!=="mechanic";if(role==="customer")await initCustomer();if(role==="mechanic")await initMechanic();else if(role!=="customer")msg("authMsg","Login berhasil, tetapi role profile belum customer/mechanic.")}
async function initCustomer(){try{services=await api("/rest/v1/service_catalog?select=*&order=name.asc");$("service").innerHTML='<option value="">Pilih layanan</option>'+services.map(s=>'<option value="'+s.id+'">'+(s.name||s.title||"Layanan")+'</option>').join("");await loadOrders()}catch(e){msg("orderMsg",e.message)}}
async function loadOrders(){try{const d=await api("/rest/v1/orders?customer_id=eq."+user.id+"&select=*&order=created_at.desc");$("orders").innerHTML=d.length?d.map(o=>'<div class="item"><b>#'+String(o.id).slice(0,8)+'</b><br>'+ (o.status||"")+'<br><span class="muted">'+(o.problem_description||o.description||"")+'</span></div>').join(""):"Belum ada order."}catch(e){$("orders").textContent=e.message}}
function geo(cb,errId){if(!navigator.geolocation){$(errId).textContent="GPS tidak tersedia";return}navigator.geolocation.getCurrentPosition(p=>cb(p.coords.latitude,p.coords.longitude),e=>$(errId).textContent="GPS gagal: "+e.message,{enableHighAccuracy:true,timeout:10000})}
async function createOrder(){try{const sid=$("service").value;if(!sid)throw Error("Pilih layanan.");const problem=$("problem").value.trim();if(!problem)throw Error("Isi keluhan motor.");let lat=profile.latitude??profile.lat??null,lon=profile.longitude??profile.lng??profile.lon??null;if(lat==null||lon==null)await new Promise((resolve,reject)=>geo((a,b)=>{lat=a;lon=b;resolve()},"gpsC"));const body={p_service_id:sid,p_brand:"-",p_model:"-",p_plate_number:"-",p_color:"-",p_year:new Date().getFullYear(),p_address_text:"Lokasi GPS",p_lat:lat,p_lng:lon,p_problem_description:problem};const d=await api("/rest/v1/rpc/create_motorcare_order",{method:"POST",body:JSON.stringify(body)});const orderId=Array.isArray(d)?d[0]?.id:d?.id;if(!orderId)throw Error("Order dibuat tetapi ID tidak ditemukan.");const a0=await api("/functions/v1/dispatch-order-v2",{method:"POST",body:JSON.stringify({order_id:orderId})});const a=Array.isArray(a0)?a0[0]:a0;msg("orderMsg",a?.assigned_mechanic_id?"Mekanik ditemukan. Menunggu konfirmasi mekanik.":"Order dibuat. Belum ada mekanik online di sekitar lokasi.",true);await loadOrders()}catch(e){msg("orderMsg","Gagal: "+e.message)}}
async function initMechanic(){await loadOffers();await loadMechanicOrders();setInterval(()=>{loadOffers();loadMechanicOrders()},5000)}
async function loadOffers(){try{const d=await api("/rest/v1/order_assignments?mechanic_id=eq."+user.id+"&select=*&order=offered_at.desc");$("offers").innerHTML=d.length?d.map(o=>'<div class="item"><b>Order '+String(o.order_id).slice(0,8)+'</b><br>Status: '+(o.accepted===true?"accepted":o.accepted===false?"rejected":"pending")+(o.accepted===null?'<div class="actions"><button onclick="respond(\''+o.id+'\',true)">Terima</button><button class="secondary" onclick="respond(\''+o.id+'\',false)">Tolak</button></div>':"")+'</div>').join(""):"Belum ada tawaran."}catch(e){$("offers").textContent=e.message}}
async function respond(id,accept){try{await api("/rest/v1/rpc/mechanic_respond_assignment",{method:"POST",body:JSON.stringify({p_assignment_id:id,p_accept:accept})});await loadOffers();await loadMechanicOrders()}catch(e){alert(e.message)}}
async function loadMechanicOrders(){try{const d=await api("/rest/v1/orders?mechanic_id=eq."+user.id+"&select=*&order=created_at.desc");$("mechanicOrders").innerHTML=d.length?d.map(o=>'<div class="item"><b>#'+String(o.id).slice(0,8)+'</b><br>'+o.status+'<div class="actions">'+["on_the_way","arrived","in_progress","completed"].map(s=>'<button onclick="statusOrder(\''+o.id+'\',\''+s+'\')">'+s+'</button>').join("")+'</div></div>').join(""):"Belum ada order aktif."}catch(e){$("mechanicOrders").textContent=e.message}}
async function statusOrder(id,status){try{await api("/rest/v1/rpc/mechanic_update_order_status",{method:"POST",body:JSON.stringify({p_order_id:id,p_status:status})});await loadMechanicOrders()}catch(e){alert(e.message)}}
async function availability(v){try{await api("/rest/v1/rpc/set_mechanic_availability",{method:"POST",body:JSON.stringify({p_available:v})});msg("gpsM",v?"Mekanik ONLINE":"Mekanik OFFLINE",true)}catch(e){msg("gpsM",e.message)}}
async function updateGps(){geo(async(a,b)=>{try{await api("/rest/v1/rpc/update_mechanic_location",{method:"POST",body:JSON.stringify({p_lat:a,p_lng:b})});$("gpsM").textContent="Lokasi terkirim: "+a.toFixed(5)+", "+b.toFixed(5)}catch(e){$("gpsM").textContent=e.message}},"gpsM")}
$("login").onclick=()=>auth("login");$("signup").onclick=()=>auth("signup");$("logout").onclick=()=>{session=null;user=null;sessionStorage.removeItem("mc_session");location.reload()};$("gpsCustomer").onclick=()=>geo((a,b)=>{$("gpsC").textContent="Lokasi: "+a.toFixed(5)+", "+b.toFixed(5);profile.latitude=a;profile.longitude=b},"gpsC");$("order").onclick=createOrder;$("online").onclick=()=>availability(true);$("offline").onclick=()=>availability(false);$("gpsMechanic").onclick=updateGps;window.respond=respond;window.statusOrder=statusOrder;window.addEventListener("online",setOnline);window.addEventListener("offline",setOnline);setOnline();
(async()=>{try{const s=sessionStorage.getItem("mc_session");if(s){session=JSON.parse(s);user=session.user;await loadProfile()}}catch{sessionStorage.removeItem("mc_session")}})();